package me.soldado.loja;

import java.util.HashMap;

public class NomeItens {

	public static HashMap<Integer, String> nomes = new HashMap<Integer, String>();
	
	public static void carregarNomes(){
        nomes.put(1, "Pedra lisa");
        nomes.put(2, "Bloco de Grama");
        nomes.put(3, "Terra");
        nomes.put(4, "Pedra");
        nomes.put(5, "Madeira");
        nomes.put(6, "Muda");
        nomes.put(7, "Rocha matriz");
        nomes.put(8, "Agua");
        nomes.put(9, "Agua");
        nomes.put(10,"Lava");
        nomes.put(11,"Lava");
        nomes.put(12,"Areia");
        nomes.put(13,"Cascalho");
        nomes.put(14,"Minério de Ouro");
        nomes.put(15,"Minério de Ferro");
        nomes.put(16,"Minério de Carvão");
        nomes.put(17,"Madeira Bruta");
        nomes.put(18,"Folhas");
        nomes.put(19,"Esponja");
        nomes.put(20,"Vidro");
        nomes.put(21,"Minério de Lápis");
        nomes.put(22,"Bloco de Lápis");
        nomes.put(23,"Ejetor");
        nomes.put(24,"Arenito");
        nomes.put(25,"Bloco de nota");
        nomes.put(26,"Cama");
        nomes.put(27,"Trilho Elétrico");
        nomes.put(28,"Trilho Detector");
        nomes.put(29,"Pistão grudento");
        nomes.put(30,"Teia");
        nomes.put(31,"Grama");
        nomes.put(32,"Arbusto Morto");
        nomes.put(33,"Pistão");
        nomes.put(34,"Pistão Ativo");
        nomes.put(35,"Lã");
        nomes.put(37,"Dende-de-Leão");
        nomes.put(38,"Papoula");
        nomes.put(39,"Cogumelo");
        nomes.put(40,"Cogumelo Vermelho");
        nomes.put(41,"Bloco de Ouro");
        nomes.put(42,"Bloco de Ferro");
        nomes.put(44,"Laje");
        nomes.put(45,"Tijolos");
        nomes.put(46,"Dinamite");
        nomes.put(47,"Estante");
        nomes.put(48,"Pedra com Musgo");
        nomes.put(49,"Obsidiana");
        nomes.put(50,"Tocha");
        nomes.put(52,"Gerador de Monstros");
        nomes.put(53,"Escada de Carvalho");
        nomes.put(54,"Baú");
        nomes.put(56,"Minério de Diamante");
        nomes.put(57,"Bloco de Diamante");
        nomes.put(58,"Mesa de Trabalho");
        nomes.put(61,"Fornalha");
        nomes.put(65,"Escada");
        nomes.put(66,"Trilho");
        nomes.put(67,"Escada de Pedra");
        nomes.put(69,"Alavanca");
        nomes.put(70,"Placa de Pressão");
        nomes.put(72,"Placa de pressão");
        nomes.put(73,"Minério de Redstone");
        nomes.put(76,"Tocha de Redstone");
        nomes.put(77,"Botão");
        nomes.put(78,"Neve");
        nomes.put(79,"Gelo");
        nomes.put(80,"Bloco de Neve");
        nomes.put(81,"Cacto");
        nomes.put(82,"Argila");
        nomes.put(84,"Jukebox");
        nomes.put(85,"Cerca de Carvalho");
        nomes.put(86,"Abóbora");
        nomes.put(87,"Rocha do Nether");
        nomes.put(88,"Areia das Almas");
        nomes.put(89,"Pedra Luminosa");
        nomes.put(90,"Portal");
        nomes.put(91,"Abóbora Acesa");
        nomes.put(95,"Vidro Tingido");
        nomes.put(96,"Alçapão de Madeira");
        nomes.put(97,"Ovo de Monstro");
        nomes.put(98,"Tijolos de Pedra");
        nomes.put(101,"Barras de Ferro");
        nomes.put(102,"Painel de Vidro");
        nomes.put(103,"Melancia");
        nomes.put(106,"Vinhas");
        nomes.put(107,"Portão de Carvalho");
        nomes.put(108,"Escadas de Tijolos");
        nomes.put(109,"Escadas de Pedra");
        nomes.put(110,"Micélio");
        nomes.put(111,"Vitória-Régia");
        nomes.put(112,"Tijolos do Nether");
        nomes.put(113,"Cerca de Tijolos");
        nomes.put(114,"Escada do Nether");
        nomes.put(116,"Mesa de Encantamentos");
        nomes.put(121,"Pedra do Fim");
        nomes.put(122,"Ovo do Dragão");
        nomes.put(123,"Lâmpada de Redstone");
        nomes.put(126,"Laje de Madeira");
        nomes.put(128,"Escada de Arenito");
        nomes.put(129,"Minério de Esmeralda");
        nomes.put(130,"Baú do Fim");
        nomes.put(131,"Gancho de Armadilha");
        nomes.put(133,"Bloco de Esmeralda");
        nomes.put(134,"Escadas de Pinheiro");
        nomes.put(135,"Escadas de Eucalipto");
        nomes.put(136,"Escada da Selva");
        nomes.put(137,"Bloco de Comando");
        nomes.put(138,"Sinalizador");
        nomes.put(139,"Parede de Pedregulho");
        nomes.put(143,"Botão");
        nomes.put(145,"Bigorna");
        nomes.put(146,"Baú com Armadilha");
        nomes.put(147,"Placa de Pressão");
        nomes.put(148,"Placa de Pressão");
        nomes.put(151,"Sensor de Luz");
        nomes.put(152,"Bloco de Redstone");
        nomes.put(153,"Minério de Quartzo");
        nomes.put(154,"Funil");
        nomes.put(155,"Bloco de Quartzo");
        nomes.put(156,"Escadas de Quartzo");
        nomes.put(157,"Trilho Ativador");
        nomes.put(158,"Liberador");
        nomes.put(159,"Argila");
        nomes.put(160,"Painle de Vidro");
        nomes.put(161,"Folhas");
        nomes.put(162,"Madeira Bruta");
        nomes.put(163,"Escadas de Acácia");
        nomes.put(164,"Escadas Escura");
        nomes.put(165,"Bloco de Slime");
        nomes.put(166,"Barreira");
        nomes.put(167,"Alçapão de Ferro");
        nomes.put(168,"Prismarinho");
        nomes.put(169,"Lanterna do Mar");
        nomes.put(170,"Fardo de Feno");
        nomes.put(171,"Carpete");
        nomes.put(172,"Argila Endurecida");
        nomes.put(173,"Bloco de Carvão");
        nomes.put(174,"Gelo Compactado");
        nomes.put(175,"Flor");
        nomes.put(179,"Arenito Vermelho");
        nomes.put(180,"Escadas Vermelhas");
        nomes.put(182,"Laje Vermelha");
        nomes.put(183,"Portão de Pinheiro");
        nomes.put(184,"Portão de Eucalipto");
        nomes.put(185,"Portão da Selva");
        nomes.put(186,"Portão Escuro");
        nomes.put(187,"Portão de Acácia");
        nomes.put(188,"Cerca de Pinheiro");
        nomes.put(189,"Cerca de Eucalipto");
        nomes.put(190,"Cerca da Selva");
        nomes.put(191,"Cerca Escura");
        nomes.put(192,"Cerca de Acácia");
        nomes.put(256,"Pá de Ferro");
        nomes.put(257,"Picareta de Ferro");
        nomes.put(258,"Machado de Ferro");
        nomes.put(259,"Isqueiro");
        nomes.put(260,"Maçã");
        nomes.put(261,"Arco");
        nomes.put(262,"Flecha");
        nomes.put(263,"Carvão");
        nomes.put(264,"Diamante");
        nomes.put(265,"Barra de Ferro");
        nomes.put(266,"Barra de Ouro");
        nomes.put(267,"Espada de Ferro");
        nomes.put(268,"Espada de Madeira");
        nomes.put(269,"Pá de Madeira");
        nomes.put(270,"Picareta de Madeira");
        nomes.put(271,"Machado de Madeira");
        nomes.put(272,"Espada de Pedra");
        nomes.put(273,"Pá de Pedra");
        nomes.put(274,"Picareta de Pedra");
        nomes.put(275,"Machado de Pedra");
        nomes.put(276,"Espada de Diamante");
        nomes.put(277,"Pá de Diamante");
        nomes.put(278,"Picareta de Diamante");
        nomes.put(279,"Machado de Diamante");
        nomes.put(280,"Graveto");
        nomes.put(281,"Tigela");
        nomes.put(282,"Ensopado");
        nomes.put(283,"Espada de Ouro");
        nomes.put(284,"Pá de Ouro");
        nomes.put(285,"Picareta de Ouro");
        nomes.put(286,"Machado de Ouro");
        nomes.put(287,"Linha");
        nomes.put(288,"Pena");
        nomes.put(289,"Pólvora");
        nomes.put(290,"Enxada de Madeira");
        nomes.put(291,"Enxada de Pedra");
        nomes.put(292,"Enxada de Ferro");
        nomes.put(293,"Enxada de Diamante");
        nomes.put(294,"Enxada de Ouro");
        nomes.put(295,"Sementes");
        nomes.put(296,"Trigo");
        nomes.put(297,"Pão");
        nomes.put(298,"Capuz de Couro");
        nomes.put(299,"Túnica de Couro");
        nomes.put(300,"Calças de Couro");
        nomes.put(301,"Botas de Couro");
        nomes.put(302,"Coifa de Malha");
        nomes.put(303,"Peitoral de Malha");
        nomes.put(304,"Calça de Malha");
        nomes.put(305,"Botas de Malha");
        nomes.put(306,"Elmo de Ferro");
        nomes.put(307,"Peitoral de Ferro");
        nomes.put(308,"Calças de Ferro");
        nomes.put(309,"Botas de Ferro");
        nomes.put(310,"Elmo de Diamante");
        nomes.put(311,"Peitoral de Diamante");
        nomes.put(312,"Calças de Diamante");
        nomes.put(313,"Botas de Diamante");
        nomes.put(314,"Elmo de Ouro");
        nomes.put(315,"Peitoral de Ouro");
        nomes.put(316,"Calças de Ouro");
        nomes.put(317,"Botas de Ouro");
        nomes.put(318,"Perdeneira");
        nomes.put(319,"Porco Crú");
        nomes.put(320,"Porco Assado");
        nomes.put(321,"Pintura");
        nomes.put(322,"Maçã Dourada");
        nomes.put(323,"Placa");
        nomes.put(324,"Porta de Carvalho");
        nomes.put(325,"Balde");
        nomes.put(326,"Balde de Água");
        nomes.put(327,"Balde de Lava");
        nomes.put(328,"Carrinho");
        nomes.put(329,"Sela");
        nomes.put(330,"Porta de Ferro");
        nomes.put(331,"Redstone");
        nomes.put(332,"Bola de Neve");
        nomes.put(333,"Bote");
        nomes.put(334,"Couro");
        nomes.put(335,"Leite");
        nomes.put(336,"Tijolo");
        nomes.put(337,"Argila");
        nomes.put(338,"Canas-de-Açúcar");
        nomes.put(339,"Papel");
        nomes.put(340,"Livro");
        nomes.put(341,"Gosma de Slime");
        nomes.put(342,"Carrinho com Baú");
        nomes.put(343,"Carrinho com Fornalha");
        nomes.put(344,"Ovo");
        nomes.put(345,"Bússola");
        nomes.put(346,"Vara de Pescar");
        nomes.put(347,"Relógio");
        nomes.put(348,"Pó de Pedra");
        nomes.put(349,"Peixe");
        nomes.put(350,"Peixe Assado");
        nomes.put(351,"Corante");
        nomes.put(352,"Osso");
        nomes.put(353,"Açucar");
        nomes.put(354,"Bolo");
        nomes.put(355,"Cama");
        nomes.put(356,"Repetidor de Redstone");
        nomes.put(357,"Biscoito");
        nomes.put(358,"Mapa");
        nomes.put(359,"Tesoura");
        nomes.put(360,"Melancia");
        nomes.put(361,"Semente de Abóbora");
        nomes.put(362,"Semente de Melancia");
        nomes.put(363,"Bife Cru");
        nomes.put(364,"Filé");
        nomes.put(365,"Frango Cru");
        nomes.put(366,"Frango Assado");
        nomes.put(367,"Carne Podre");
        nomes.put(368,"Pérola do Fim");
        nomes.put(369,"Vara de Blaze");
        nomes.put(370,"Lágrima de Ghast");
        nomes.put(371,"Pepita de Ouro");
        nomes.put(372,"Fungo do Nether");
        nomes.put(373,"Poção");
        nomes.put(374,"Frasco de Vidro");
        nomes.put(375,"Olho de Aranha");
        nomes.put(376,"Olho de Aranha Fermentado");
        nomes.put(377,"Pó de Blaze");
        nomes.put(378,"Creme de Magma");
        nomes.put(379,"Suporte de Poções");
        nomes.put(380,"Caldeirão");
        nomes.put(381,"Olho do Fim");
        nomes.put(382,"Melancia Reluzente");
        nomes.put(383,"Invocador");
        nomes.put(384,"Frasco de Encantamentos");
        nomes.put(385,"Bola de Fogo");
        nomes.put(386,"Pena e Livro");
        nomes.put(387,"Livro Escrito");
        nomes.put(388,"Esmeralda");
        nomes.put(389,"Moldura");
        nomes.put(390,"Vaso de Flor");
        nomes.put(391,"Cenoura");
        nomes.put(392,"Batata");
        nomes.put(393,"Batata Assada");
        nomes.put(394,"Batata Venenosa");
        nomes.put(395,"Mapa em Branco");
        nomes.put(396,"Cenoura Dourada");
        nomes.put(397,"Cabeça");
        nomes.put(398,"Cenoura no Palito");
        nomes.put(399,"Estrela do Nether");
        nomes.put(400,"Torta de Abóbora");
        nomes.put(401,"Fogos de Artifício");
        nomes.put(402,"Estrela de Fogos");
        nomes.put(403,"Livro Encantado");
        nomes.put(404,"Comparador");
        nomes.put(405,"Tijolo do Nether");
        nomes.put(406,"Quartzo do Nether");
        nomes.put(407,"Carrinho com Dinamite");
        nomes.put(408,"Carrinho com Funil");
        nomes.put(409,"Fragmento de Prismarinho");
        nomes.put(410,"Cristais de Prismarinho");
        nomes.put(411,"Coelho Cru");
        nomes.put(412,"Coelho Assado");
        nomes.put(413,"Ensopado de Coelho");
        nomes.put(414,"Pé de Coelho");
        nomes.put(415,"Pelo de Coelho");
        nomes.put(416,"Suporte de Armaduras");
        nomes.put(417,"Armadura de Cavalo");
        nomes.put(418,"Armadura de Cavalo");
        nomes.put(419,"Armadura de Cavalo");
        nomes.put(420,"Laço");
        nomes.put(421,"Etiqueta");
        nomes.put(423,"Carneiro Cru");
        nomes.put(424,"Carneiro Assado");
        nomes.put(425,"Estandarte");
        nomes.put(427,"Porta de Pinheiro");
        nomes.put(428,"Porta de Eucalipto");
        nomes.put(429,"Porta da Selva");
        nomes.put(430,"Porta de Acácia");
        nomes.put(431,"Porta Escura");
        nomes.put(2256,"Disco de Música");
	}
}